import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/Component/Header'
import Footer from '@/Component/Footer'
import styles from './LayOut.module.css'
import Head from 'next/head'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children }: { children: React.ReactNode }) {

  function btnhandle() { }
  return (
    <html lang="en">
      <body className={styles.LayOut}>
        <Header />
        <div className={styles.divs}>
          <button onClick={btnhandle}>按钮</button>
        </div>

        <Home />
        <Footer />
      </body>

    </html>
  )
}
