import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/assets/font/iconfont.css'
import '@/assets/css/iconfont.css'
import Footer from '@/Component/Footer'
import Header from '@/Component/Header'
import styles from './LayOut.module.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
