import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@/assets/font/iconfont.css'
import '@/assets/css/iconfont.css'
import Footer from '@/Component/Footer'
import Header from '@/Component/Header'
import styles from './LayOut.module.css'
import Head from 'next/head'
import Script from 'next/script'
import FlyBird from '@/Component/FlyBird'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <div >

          <Header />

          {children}
          {/* </FlyBird> */}
          <Footer />





        </div>
      </body>
      <script src='https://yanyunfeng.com/scripts/three.min.js' async></script>
    </html>
  )
}
